from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, ForeignKey, Float
from sqlalchemy.sql import func
from app.database import Base


class Alert(Base):
    """
    Law enforcement command alerts generated by watchlist hits or suspicious anomalies.
    Contains fields: alert_id, priority (CRITICAL/HIGH/MEDIUM), vehicle, plate, camera, location, timestamp, confidence, evidence_image.
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(100), unique=True, index=True, nullable=True)
    title = Column(String(200), nullable=False)
    alert_type = Column(String(100), nullable=False, default="WATCHLIST_MATCH")
    priority = Column(String(50), default="HIGH")  # CRITICAL, HIGH, MEDIUM
    severity = Column(String(50), default="HIGH")
    message = Column(Text, nullable=False)
    vehicle = Column(String(150), nullable=True)
    plate = Column(String(50), index=True, nullable=True)
    license_plate = Column(String(50), nullable=True)
    camera_id = Column(Integer, ForeignKey("cameras.id"), nullable=True)
    camera_name = Column(String(150), nullable=True)
    location = Column(String(200), nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    confidence = Column(Float, default=0.90)
    evidence_image = Column(String(500), nullable=True)
    snapshot_url = Column(String(500), nullable=True)
    plate_crop_url = Column(String(500), nullable=True)
    dna_id = Column(String(100), nullable=True)
    is_acknowledged = Column(Boolean, default=False)
    acknowledged_by = Column(String(100), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
